param(
    [string]$Configuration = "Release"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$projectPath = Join-Path $projectRoot "TidyDock.csproj"
$msbuild = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"
$distRoot = Join-Path $projectRoot "dist"
$portableRoot = Join-Path $distRoot "TidyDock-portable"
$outputDir = Join-Path $projectRoot "bin\$Configuration"
$exePath = Join-Path $outputDir "TidyDock.exe"
$iconPath = Join-Path $projectRoot "assets\TidyDock.ico"
$iconScript = Join-Path $PSScriptRoot "New-AppIcon.ps1"

if (-not (Test-Path $msbuild)) {
    throw "MSBuild not found: $msbuild"
}

if (-not (Test-Path $iconPath)) {
    if (-not (Test-Path $iconScript)) {
        throw "Icon missing and icon generator not found: $iconScript"
    }
    & powershell -ExecutionPolicy Bypass -File $iconScript
}

Get-Process -Name TidyDock -ErrorAction SilentlyContinue | Stop-Process -Force

& $msbuild $projectPath /p:Configuration=$Configuration /verbosity:minimal
if ($LASTEXITCODE -ne 0) {
    throw "Build failed."
}

if (-not (Test-Path $exePath)) {
    throw "Executable not found: $exePath"
}

if (Test-Path $portableRoot) {
    $resolvedDist = Resolve-Path $distRoot
    $resolvedPortable = Resolve-Path $portableRoot
    if (-not $resolvedPortable.Path.StartsWith($resolvedDist.Path, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to clean unexpected path: $resolvedPortable"
    }
    Remove-Item -LiteralPath $portableRoot -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $portableRoot | Out-Null
Copy-Item -LiteralPath $exePath -Destination (Join-Path $portableRoot "TidyDock.exe")
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "Install-CurrentUser.ps1") -Destination (Join-Path $portableRoot "Install-CurrentUser.ps1")
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "Uninstall-CurrentUser.ps1") -Destination (Join-Path $portableRoot "Uninstall-CurrentUser.ps1")
Copy-Item -LiteralPath $iconPath -Destination (Join-Path $portableRoot "TidyDock.ico")
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "Test-Portable.ps1") -Destination (Join-Path $portableRoot "Test-Portable.ps1")

$readme = @"
TidyDock Portable
=================

Run:
  TidyDock.exe

Install for current user:
  powershell -ExecutionPolicy Bypass -File .\Install-CurrentUser.ps1

Install and launch:
  powershell -ExecutionPolicy Bypass -File .\Install-CurrentUser.ps1 -Launch

Install, launch, and start with Windows:
  powershell -ExecutionPolicy Bypass -File .\Install-CurrentUser.ps1 -Launch -StartWithWindows

Uninstall:
  powershell -ExecutionPolicy Bypass -File .\Uninstall-CurrentUser.ps1

Verify package:
  powershell -ExecutionPolicy Bypass -File .\Test-Portable.ps1

Data location:
  %APPDATA%\TidyDock
  %APPDATA%\TidyDock\config\settings.json
  %APPDATA%\TidyDock\cache\icons
  %APPDATA%\TidyDock\logs\error.log

Notes:
  - A fresh config starts empty; users manually add Dock items.
  - Dock item add, remove, rename, icon change, and reorder require edit mode.
  - Dock background opacity can be set to 0 for a fully transparent Dock surface.
  - TidyDock does not scan the desktop.
  - TidyDock does not monitor running apps.
  - TidyDock does not index files in the background.
  - TidyDock does not replace the Windows taskbar.
  - TidyDock does not upload data or make network requests.
  - Folder contents are read only when a folder item is clicked.
  - Settings includes open config folder, open log folder, clear icon cache, reset config, and exit app.

Build:
  Generated by scripts\Build-Portable.ps1
"@

Set-Content -LiteralPath (Join-Path $portableRoot "README.txt") -Value $readme -Encoding UTF8

$zipPath = Join-Path $distRoot "TidyDock-portable.zip"
if (Test-Path $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}

Compress-Archive -LiteralPath $portableRoot -DestinationPath $zipPath -Force

Write-Host "Portable package:"
Write-Host $portableRoot
Write-Host $zipPath

